apiVersion: v1
kind: ReplicationController
metadata:
  name: Labs-k8s-app1-rc
spec:
  template:
    metadata:
      name: Labs-k8s-app1-pod
      labels:
        app: app1
        type: Front-End
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3