apiVersion: v1
kind: ReplicationController
metadata:
  name: labs-k8s-app1-rc
spec:
  template:
    metadata:
      name: labs-k8s-app1-rc
      labels:
        app: app1
        type: Front-End
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 20